spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://www.qianzhikang.cn:3306/zty-database
    username: root
    password:
  jackson:
    date-format: "yyyy-MM-dd HH:mm:ss"
    time-zone: Asia/Shanghai

mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  config: classpath:log/logback-spring.xml

app:
  constant:
    # 默认时间容错范围 （单位：秒）
    default-time-tolerance: 15